# map command+<key> to TUI shortcuts
# this needs to be handled at the terminal level as osx does not expose Command key as a regular key modifier
# cmd+b > ctrl+b
map cmd+b send_text all \x02

# herdr: select tab. cmd+0..9 > cmd+b + 0..9
map cmd+0 send_text all \x020
map cmd+1 send_text all \x021
map cmd+2 send_text all \x022
map cmd+3 send_text all \x023
map cmd+4 send_text all \x024
map cmd+5 send_text all \x025
map cmd+6 send_text all \x026
map cmd+7 send_text all \x027
map cmd+8 send_text all \x028
map cmd+9 send_text all \x029

# herdr: workspace
map cmd+g send_text all \x02g
map cmd+w send_text all \x02w
map cmd+shift+w send_text all \x02W
map cmd+shift+n send_text all \x02N

# herdr: tab
map cmd+t send_text all \x02t
map cmd+shift+t send_text all \x02T
map cmd+[ send_text all \x02p
map cmd+] send_text all \x02n

# herdr: pane
map cmd+\ send_text all \x02v
map cmd+- send_text all \x02-
map cmd+enter send_text all \x02z
map cmd+x send_text all \x02x
map cmd+k send_text all \x02k
map cmd+j send_text all \x02j
map cmd+h send_text all \x02h
map cmd+l send_text all \x02l

