hide_window_decorations yes

tab_bar_min_tabs 1
tab_bar_style hidden

font_family      family="MesloLGMDZ Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0

# map command+<key> to tmux default shortcuts
# this needs to be handled at the terminal level as osx does not expose Command key to Tmux.
# select windows
map cmd+1 send_text all \x021
map cmd+2 send_text all \x022
map cmd+3 send_text all \x023
map cmd+4 send_text all \x024
map cmd+5 send_text all \x025
map cmd+6 send_text all \x026
map cmd+7 send_text all \x027
map cmd+8 send_text all \x028
map cmd+9 send_text all \x029
map cmd+0 send_text all \x020
map cmd+t send_text all \x02c
map cmd+w send_text all \x02&

# move between panes
map cmd+up send_text all \x02\e[A
map cmd+down send_text all \x02\e[B
map cmd+left send_text all \x02\e[D
map cmd+right send_text all \x02\e[C

# resize pane
map cmd+shift+up send_text all \x02\e[1;5A
map cmd+shift+down send_text all \x02\e[1;5B
map cmd+shift+left send_text all \x02\e[1;5D
map cmd+shift+right send_text all \x02\e[1;5C

# split, zoom, close pane
map cmd+\ send_text all \x02%
map cmd+- send_text all \x02"
map cmd+enter send_text all \x02z
map cmd+x send_text all \x02xy

map cmd+/ send_text all \x02[         #copy mode
map cmd+shift+v send_text all \x02]   #paste buffer

include theme.conf
