hide_window_decorations yes

tab_bar_min_tabs 1
tab_bar_style hidden

font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16

macos_option_as_alt yes

include theme.conf
include keymap.conf

shell herdr
close_on_child_death yes
startup_session herdr
